### ISSUE TITLE
how would you construct `data` in real case scenario?

### ISSUE THREAD

**Issue by miktam** [SylTi/solidity-smart-contracts#2]
https://github.com/SylTi/solidity-smart-contracts/blob/69ba7acbd52de4cc4c1fc294105633cee556915c/test/MultiSig.test.js#L69

**Comment by SylTi** [comment]
Let's say you wanted the payment to be to a contract, and that contract want the payment on a function `execute()` 
You would you would need to send the result of `bytes4(keccak256("execute()")` as `data`.

You can find out more about it here http://solidity.readthedocs.io/en/v0.4.24/types.html#members-of-addresses in "call, callcode and delegatecall"
